# Prepare environment.yml file
name: cytotrace2-py
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python=3.9.19
  - anndata
  - numpy
  - pandas
  - scanpy
  - scipy
  - scikit-learn=1.0.2
  - pytorch=2.0.0
  - notebook # optional, for jupyter notebook
  - r-rann=2.6.1
  - r-seurat=4.3.0.1
  - r-seuratobject=5.0.0
  - r-matrix=1.6.1
  - r-ggplot2
  - r-data.table
  - r-dplyr
  - r-argparse
